name: adrewards_pro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Backend & Auth
  supabase_flutter: ^2.12.0
  google_sign_in: ^6.2.1
  
  # UI Design & Animations
  google_fonts: ^6.1.0          # Modern text style ke liye
  flutter_fortune_wheel: ^1.2.0 # Spin wheel animation ke liye
  scratcher: ^2.4.0             # Scratch card effect ke liye
  
  # Local Storage (Timer aur data save karne ke liye)
  shared_preferences: ^2.5.4    

  # Monetization (Ads)
  unity_ads_plugin: ^0.3.11     # Unity ads ke liye

  # State Management (Optional par future me chahiye hoga)
  provider: ^6.1.1
  share_plus: ^12.0.1
  flutter_dotenv: ^6.0.0
  device_info_plus: ^12.3.0
  dart_ipify: ^1.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # ðŸ‘‡ NAYA: Package add kiya

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/icon/ # ðŸ‘‡ NAYA: Folder path de diya taaki image mil jaye

# ðŸ‘‡ NAYA: App icon generate karne ki settings
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21